# Site settings
title: 
highlighter: false
email: ying.zhao@quantumii.com
description: > # 
baseurl: "/yingblog" # the subpath of your site, e.g. /blog/
url: "http://www.quantumii.com" # the base hostname & protocol for your site
twitter_username: yzhao95014
facebook_username: ying.zhao.161
github_username:  yzhao95014
instagram_username: jezhou

# Build settings
markdown: kramdown
