# Site settings
title: 
highlighter: false
email: jez017@ucsd.edu
description: > # 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.thetophu.com" # the base hostname & protocol for your site
facebook_username: pages/Quantum-Intelligence-Inc/117560491604386
sponsor_1: http://www.ccleanenergy.com
sponsor_2: http://www.quantumii.com
# Build settings
markdown: kramdown
